### ISSUE TITLE
The Tool Is Generating A PS1 String With Unexpected Leading Characters 

### ISSUE THREAD

**Issue by jmartin111** [Scriptim/bash-prompt-generator#13]
This prompt: 

- PS1='\[\e[0;1;38;5;212m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2) \[\e[0;1;38;5;46m\]\u\[\e[0;38;5;227m\]@\[\e[0;1;38;5;46m\]\h\[\e[0m\]:\[\e[0;1;38;5;45m\]/\[\e[0;1;38;5;45m\]\W\[\e[0;1;38;5;226m\]# \[\e[0m\]'

is resulting in the following prompt when set in my .bashrc file. Screenshot of the generator page below

- ]main jeff@machine:/var$

Where are these two leading characters coming from?

- ]

**Note: view this in plaintext mode so the markdown editor doesn't render them differently. This is also important because the renderer is removing non-escaped backslashes**

<img width="548" alt="Bash Prompt Generator-2022-09-12" src="https://user-images.githubusercontent.com/8364306/189782191-386e1250-4aff-4c12-bf9f-c9aeaea9c549.png">

**Comment by Scriptim** [comment]
I cannot reproduce this issue. The prompt string works perfectly fine for me:
![screenshot_000](https://user-images.githubusercontent.com/13003924/189843301-030baf73-0a99-4b6f-94f1-218fdf2ab7c5.png)

Can you post the output from `git branch 2>/dev/null`?

**Comment by jmartin111** [comment]
You are seeing the issue but the characters aren’t rendering.

Notice how your prompt is offset two spaces to the right? 

I see the same thing on my MacBook bash terminal. The original issue was seen on WSL and somehow that environment is rendering the special characters as opposed to just spaces.

**Comment by jmartin111** [comment]
If I remove the GIt branch portion, everything looks fine. Please see the attached screenshot.

**Comment by Scriptim** [comment]
> Notice how your prompt is offset two spaces to the right?

The prompt ist offset by one space. This is the space character element that comes between the *Git branch* and the *username*. It appears to be an offset here only because I was in a directory that does not contain a git repo. In a git repository, the prompt looks like this:

![screenshot](https://user-images.githubusercontent.com/13003924/190102760-b385a637-64e4-46d4-bf9e-9d2540e64e67.png)

**Comment by jmartin111** [comment]
***@***.***:~/projects/tmp$ git status
On branch test-branch

No commits yet

nothing to commit (create/copy files and use "git add" to track)
***@***.***:~/projects/tmp$ git branch | grep '^*' | cat -A
cat: illegal option -- A
usage: cat [-belnstuv] [file ...]
***@***.***:~/projects/tmp$

**Comment by Scriptim** [comment]
That's odd. What platform are you on exactly (operating system version, bash version, terminal software)?

Which output does `git branch | grep '^*'` produce (without the `cat` pipe which apparently has no `-A` option in your system's implementation)?

**Comment by jmartin111** [comment]
Thats he odd thing. ‘Git branch’ returns nothing at all even by itself. I am looking in to that. You can probably close this ticket. I have found an alternate PS1 builder that does what I need.


Thanks for all your time and help; I really apprecitate it.

**Comment by Scriptim** [comment]
> I have found an alternate PS1 builder that does what I need.

Just out of interest, could you show me the working PS1 string from the other tool so I can see what that one does differently?
