### ISSUE TITLE
PROMPT_DIRTRIM option 

### ISSUE THREAD

**Issue by jxu** [Scriptim/bash-prompt-generator#22]
Having an option to include `PROMPT_DIRTRIM=2` or something in the Output box for copy pasting would be neat. I had to look up how to do it.

**Comment by Scriptim** [comment]
I believe this would have added too much complexity to the tool. We would have needed an additional input field on `Working Directory` elements (although the value would apply globally), the example preview would have had to support this option, and even the parser would have required an additional input field specifically for `PROMPT_DIRTRIM`'s value. However, I added a hint below the output to make the user aware of the existence of such an option.
