### ISSUE TITLE
Git branch bug

### ISSUE THREAD

**Issue by jxu** [Scriptim/bash-prompt-generator#25]
When I try the output given:

    PROMPT_COMMAND='PS1_CMD1=$($(git branch 2>/dev/null | grep '"'"'*'"'"' | colrm 1 2))' 

My bash tries to run the branch name as a command (e.g. `Command 'master' not found`). I think there is an extra subshell, that is set of `$(...)`. Without it, it works.

**Comment by Scriptim** [comment]
Note: Maybe we should consider using [git-prompt.sh](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh) for the git element.
