### ISSUE TITLE
Conditional color based on last exit code

### ISSUE THREAD

**Issue by jxu** [Scriptim/bash-prompt-generator#27]
Something interesting my friend told me about is having the prompt symbol colored based on whether or not the last command succeeded, i.e. the value of `$?`:

![image](https://github.com/Scriptim/bash-prompt-generator/assets/7989982/0b0c7b27-00bf-4749-a349-4ba76e398812)

Is conditional coloring or symbols too much complexity?

**Comment by Scriptim** [comment]
That is not a built-in feature of the Bash prompt as far as I know. So you'd have to [write a custom function](https://stackoverflow.com/a/43015676) (e.g., in your `.bashrc` or inline) that outputs the colored prompt symbol. Then you can use the `Command` element in the prompt generator and configure it to call the function.

For instance, you could use the following command:
```bash
if [[ "$?" == "0" ]]; then echo -e "\e[32m✓\e[0m"; else echo -e "\e[31m✘\e[0m"; fi
```
