### ISSUE TITLE
Just share my prompt config.

### ISSUE THREAD

**Issue by lilj** [Scriptim/bash-prompt-generator#29]
PSX="\[\e[38;5;51;1m\]ヽ༼ຈل͜ຈ༽ﾉ\[\e[0m\]"
GIT_PS1="\$(git rev-parse --abbrev-ref HEAD 2>/dev/null|sed -e 's/\(.*\)/ git(\1) /')"
PS1="\n$PSX\n\[\e[38;5;21;48;5;249m\] \u@\h:\[\e[0m\]\[\e[38;5;20;48;5;35m\] \w \[\e[38;5;198;48;5;252m\]$GIT_PS1\[\e[0m\]\n\$ "

<img width="456" alt="image" src="https://github.com/user-attachments/assets/dae2b92f-00a1-47ae-a377-87428181fef1">

**Comment by edswangren** [comment]
I threw up a little in my mouth just now, but  I'm genuinely happy for you.  🚫 🧢

**Comment by Scriptim** [comment]
Closing this because it is not really an issue, but I might reconsider when I decide to tackle #23.
