### ISSUE TITLE
Add colours feature

### ISSUE THREAD

**Issue by alex-konkov** [Scriptim/bash-prompt-generator#31]
### Feature Description

Add ability to colourize text.

### Not a duplicate

- [X] This is not a duplicate

### Want to Implement

- [ ] I want to implement this feature

**Comment by Scriptim** [comment]
If you select a `Text` element, you can already change its colors under *Properties*:
![bash_prompt_generator_text_properties](https://github.com/user-attachments/assets/40fc4c13-eee4-49ca-92e9-95bfba7bff35)

The resulting prompt will look like this:
![bash_prompt_generator_text_properties_preview](https://github.com/user-attachments/assets/319e2b32-c473-4db3-abf1-ed0edaaa13ad)
