### ISSUE TITLE
Add the ability to put characters around git branch

### ISSUE THREAD

**Issue by sketchbuch** [Scriptim/bash-prompt-generator#4]
I want git branch in brackets like this:

`user@host: ~/projects/project-a (master) $`

But I only want the brackets to be rendered in the prompt if there is a git branch.

**Comment by Scriptim** [comment]
You can write a bash function that produces your desired output and use the _Command_ element in the prompt generator.

---

For example, define this function in your `.bashrc` file:
```bash
function git_branch() {
    GIT_BRANCH="$(git branch 2>/dev/null | grep '^*' | colrm 1 2)"
    if [ -n "$GIT_BRANCH" ]; then
        echo "($GIT_BRANCH)"
    fi
}
```

Then create a _Command_ element and put "`git_branch`" in the according field under _Properties_.

**Comment by sketchbuch** [comment]
That is perfect thanks
