### ISSUE TITLE
Add the ability to paste an existing bash prompt string created with the generator

### ISSUE THREAD

**Issue by sketchbuch** [Scriptim/bash-prompt-generator#5]
If I use the string I may want to edit it, it would be useful if you could just paste my existing bash prompt created by this editor into the UI and have it assemble all the parts again so I can change colours, or rearrange things without having to build the entire prompt from scratch again

**Comment by Scriptim** [comment]
This feature has been planned for a long time and there was also a first attempt to implement it (#1). I can't promise if and when I'll get around to taking care of it.

**Comment by Scriptim** [comment]
By the way, if you created your bash prompt on the website, it should be stored in local storage so that you can continue working on it the next time you visit the site without having to redo everything from scratch.
